[package]
name = "spectra"
version = "0.1.0"
license = "BSD-3-Clause"
authors = ["Dimitri Sabadie <dimitri.sabadie@gmail.com>"]
description = "Demoscene framework"
keywords = ["demoscene"]
build = "build.rs"

homepage = "https://github.com/phaazon/spectra"
repository = "https://github.com/phaazon/spectra"
documentation = "http://phaazon.github.io/spectra"

[[bin]]
name = "spectra"
path = "spectra/src/main.rs"
doc = false

[dependencies]
alto = "1.0"
any-cache = "0.1"
chrono = "0.3"
clap = "2.19"
#luminance = "0.18"
luminance = { path = "../../luminance" }
gl = "0.6"
glfw = "0.13"
image = "0.12"
nalgebra = "0.10"
notify = "2.6"
num = "0.1"
rusttype = "0.2"
serde = "0.9"
serde_derive = "0.9"
serde_json = "0.9"
vorbis = "0.1"
wavefront_obj = "5.0"

[dev-dependencies]
rand = "0.3" # for unit tests
