[package]
name = "ion"
version = "0.1.0"
license = "BSD-3-Clause"
authors = ["Dimitri Sabadie <dimitri.sabadie@gmail.com>"]
description = "Demoscene framework"
keywords = ["demoscene"]

homepage = "https://github.com/phaazon/ion"
repository = "https://github.com/phaazon/ion"
documentation = "http://phaazon.github.io/ion"

[features]
default = []
debug = ["hot-shader", "hot-texture"]
hot-shader = ["notify"]
hot-texture = ["notify"]

[dependencies]
luminance = "0.7.0"
luminance-gl = "0.6.1"
gl = "0.5.2"
glfw = { version = "0.9.1", default-features = false }
image = "0.10.1"
nalgebra = "0.10.0"
openal-rs = "0.1.4"
vorbis = "0.0.14"

# optional dependencies (used in conjunction with features)
notify = { version = "2.6.3", optional = true }

[dev-dependencies]
rand = "0.3.14" # for unit tests

[replace]
"luminance:0.7.0" = { git = "https://github.com/phaazon/luminance-rs.git" }
"luminance-gl:0.6.1" = { git = "https://github.com/phaazon/luminance-gl-rs.git" }
