[package]
name = "ion"
version = "0.1.0"
license = "BSD-3-Clause"
authors = ["Dimitri Sabadie <dimitri.sabadie@gmail.com>"]
description = "Demoscene framework"
keywords = ["demoscene"]

homepage = "https://github.com/phaazon/ion"
repository = "https://github.com/phaazon/ion"
documentation = "http://phaazon.github.io/ion"

[features]
default = ["debug"]
debug = ["hot-resource"]
hot-resource = ["notify"]

[dependencies]
luminance = { git = "https://github.com/phaazon/luminance-rs" }
luminance-gl = { git = "https://github.com/phaazon/luminance-rs" }
gl = "0.5.2"
glfw = { version = "0.9.1", default-features = false }
image = "0.10.1"
nalgebra = "0.10.0"
openal-rs = "0.1.4"
vorbis = "0.0.14"
wavefront_obj = { git = "https://github.com/phaazon/wavefront_obj.git", branch = "shape-fields", version = "4.0.0" }

# optional dependencies (used in conjunction with features)
notify = { version = "2.6.3", optional = true }

[dev-dependencies]
rand = "0.3.14" # for unit tests
