[package]
name = "ion"
version = "0.1.0"
license = "BSD-3-Clause"
authors = ["Dimitri Sabadie <dimitri.sabadie@gmail.com>"]
description = "Demoscene framework"
keywords = ["demoscene"]

homepage = "https://github.com/phaazon/ion"
repository = "https://github.com/phaazon/ion"
documentation = "http://phaazon.github.io/ion"

[features]
default = []
hot-shader = ["notify"]

[dependencies]
luminance = "0.6.2"
luminance-gl = "0.5.3"
gl = "0.5.2"
glfw = { version = "0.9.1", default-features = false }
image = "0.10.1"
nalgebra = { git = "https://github.com/phaazon/nalgebra.git", rev = "1fdd8979afa464d1a13d0bfe926e0d9aaab0ee1a" }
openal-rs = "0.1.4"
vorbis = "0.0.14"

# optional dependencies (used in conjunction with features)
notify = { version = "2.6.3", optional = true }

[dev-dependencies]
rand = "0.3.14" # for unit tests
