[package]
name = "spectra"
version = "0.1.0"
license = "BSD-3-Clause"
authors = ["Dimitri Sabadie <dimitri.sabadie@gmail.com>"]
description = "Demoscene framework"
keywords = ["demoscene"]
build = "build.rs"

homepage = "https://github.com/phaazon/spectra"
repository = "https://github.com/phaazon/spectra"
documentation = "http://phaazon.github.io/spectra"

[[bin]]
name = "spectra"
path = "spectra/src/main.rs"
doc = false

[dependencies]
alto = "1.0.5"
any-cache = { git = "https://github.com/phaazon/any-cache.git" }
chrono = "0.3"
clap = "2.19.0"
luminance = { git = "https://github.com/phaazon/luminance-rs" }
gl = "0.5.2"
glfw = "0.13.0"
image = "0.10.1"
nalgebra = "0.10.0"
notify = "2.6.3"
num = "0.1.36"
rusttype = "0.2.1"
serde = "0.8.16"
serde_derive = "0.8.16"
serde_json = "0.8.3"
vorbis = "0.0.14"
wavefront_obj = "5.0.0"

[dev-dependencies]
rand = "0.3.14" # for unit tests
