[package]
name = "spectra"
version = "0.1.0"
license = "BSD-3-Clause"
authors = ["Dimitri Sabadie <dimitri.sabadie@gmail.com>"]
description = "Demoscene framework"
keywords = ["demoscene"]
build = "build.rs"

homepage = "https://github.com/phaazon/spectra"
repository = "https://github.com/phaazon/spectra"
documentation = "http://phaazon.github.io/spectra"

[[bin]]
name = "spectra"
path = "spectra/src/main.rs"

[features]
default = ["debug"]
debug = ["hot-resource"]
hot-resource = ["notify", "time"]

[dependencies]
clap = "2.19.0"
luminance = { git = "https://github.com/phaazon/luminance-rs" }
luminance-gl = { git = "https://github.com/phaazon/luminance-rs" }
gl = "0.5.2"
glfw = { version = "0.9.1", default-features = false }
image = "0.10.1"
nalgebra = "0.10.0"
openal-rs = "0.1.4"
serde = "0.8.16"
serde_derive = "0.8.16"
serde_json = "0.8.3"
vorbis = "0.0.14"
wavefront_obj = "5.0.0"

# optional dependencies (used in conjunction with features)
notify = { version = "2.6.3", optional = true }
time = { version = "0.1.35", optional = true }

[dev-dependencies]
rand = "0.3.14" # for unit tests
